// Generated by gencpp from file chat_pkg/ChatMessage.msg
// DO NOT EDIT!


#ifndef CHAT_PKG_MESSAGE_CHATMESSAGE_H
#define CHAT_PKG_MESSAGE_CHATMESSAGE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace chat_pkg
{
template <class ContainerAllocator>
struct ChatMessage_
{
  typedef ChatMessage_<ContainerAllocator> Type;

  ChatMessage_()
    : sender()
    , message()  {
    }
  ChatMessage_(const ContainerAllocator& _alloc)
    : sender(_alloc)
    , message(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _sender_type;
  _sender_type sender;

   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _message_type;
  _message_type message;





  typedef boost::shared_ptr< ::chat_pkg::ChatMessage_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::chat_pkg::ChatMessage_<ContainerAllocator> const> ConstPtr;

}; // struct ChatMessage_

typedef ::chat_pkg::ChatMessage_<std::allocator<void> > ChatMessage;

typedef boost::shared_ptr< ::chat_pkg::ChatMessage > ChatMessagePtr;
typedef boost::shared_ptr< ::chat_pkg::ChatMessage const> ChatMessageConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::chat_pkg::ChatMessage_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::chat_pkg::ChatMessage_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::chat_pkg::ChatMessage_<ContainerAllocator1> & lhs, const ::chat_pkg::ChatMessage_<ContainerAllocator2> & rhs)
{
  return lhs.sender == rhs.sender &&
    lhs.message == rhs.message;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::chat_pkg::ChatMessage_<ContainerAllocator1> & lhs, const ::chat_pkg::ChatMessage_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace chat_pkg

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::chat_pkg::ChatMessage_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::chat_pkg::ChatMessage_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::chat_pkg::ChatMessage_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::chat_pkg::ChatMessage_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::chat_pkg::ChatMessage_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::chat_pkg::ChatMessage_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::chat_pkg::ChatMessage_<ContainerAllocator> >
{
  static const char* value()
  {
    return "985ef42f02a992c58d5de728edeb121e";
  }

  static const char* value(const ::chat_pkg::ChatMessage_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x985ef42f02a992c5ULL;
  static const uint64_t static_value2 = 0x8d5de728edeb121eULL;
};

template<class ContainerAllocator>
struct DataType< ::chat_pkg::ChatMessage_<ContainerAllocator> >
{
  static const char* value()
  {
    return "chat_pkg/ChatMessage";
  }

  static const char* value(const ::chat_pkg::ChatMessage_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::chat_pkg::ChatMessage_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string sender\n"
"string message\n"
;
  }

  static const char* value(const ::chat_pkg::ChatMessage_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::chat_pkg::ChatMessage_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.sender);
      stream.next(m.message);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ChatMessage_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::chat_pkg::ChatMessage_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::chat_pkg::ChatMessage_<ContainerAllocator>& v)
  {
    s << indent << "sender: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.sender);
    s << indent << "message: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.message);
  }
};

} // namespace message_operations
} // namespace ros

#endif // CHAT_PKG_MESSAGE_CHATMESSAGE_H
