// Generated by gencpp from file bot_simulator/bot_pose.msg
// DO NOT EDIT!


#ifndef BOT_SIMULATOR_MESSAGE_BOT_POSE_H
#define BOT_SIMULATOR_MESSAGE_BOT_POSE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace bot_simulator
{
template <class ContainerAllocator>
struct bot_pose_
{
  typedef bot_pose_<ContainerAllocator> Type;

  bot_pose_()
    : x(0.0)
    , y(0.0)
    , facing()  {
    }
  bot_pose_(const ContainerAllocator& _alloc)
    : x(0.0)
    , y(0.0)
    , facing(_alloc)  {
  (void)_alloc;
    }



   typedef float _x_type;
  _x_type x;

   typedef float _y_type;
  _y_type y;

   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _facing_type;
  _facing_type facing;





  typedef boost::shared_ptr< ::bot_simulator::bot_pose_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::bot_simulator::bot_pose_<ContainerAllocator> const> ConstPtr;

}; // struct bot_pose_

typedef ::bot_simulator::bot_pose_<std::allocator<void> > bot_pose;

typedef boost::shared_ptr< ::bot_simulator::bot_pose > bot_posePtr;
typedef boost::shared_ptr< ::bot_simulator::bot_pose const> bot_poseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::bot_simulator::bot_pose_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::bot_simulator::bot_pose_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::bot_simulator::bot_pose_<ContainerAllocator1> & lhs, const ::bot_simulator::bot_pose_<ContainerAllocator2> & rhs)
{
  return lhs.x == rhs.x &&
    lhs.y == rhs.y &&
    lhs.facing == rhs.facing;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::bot_simulator::bot_pose_<ContainerAllocator1> & lhs, const ::bot_simulator::bot_pose_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace bot_simulator

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::bot_simulator::bot_pose_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::bot_simulator::bot_pose_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::bot_simulator::bot_pose_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::bot_simulator::bot_pose_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::bot_simulator::bot_pose_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::bot_simulator::bot_pose_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::bot_simulator::bot_pose_<ContainerAllocator> >
{
  static const char* value()
  {
    return "d7659f9c689cfd66a9a6fb85b21deb2b";
  }

  static const char* value(const ::bot_simulator::bot_pose_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xd7659f9c689cfd66ULL;
  static const uint64_t static_value2 = 0xa9a6fb85b21deb2bULL;
};

template<class ContainerAllocator>
struct DataType< ::bot_simulator::bot_pose_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bot_simulator/bot_pose";
  }

  static const char* value(const ::bot_simulator::bot_pose_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::bot_simulator::bot_pose_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float32 x\n"
"float32 y\n"
"string facing\n"
;
  }

  static const char* value(const ::bot_simulator::bot_pose_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::bot_simulator::bot_pose_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.x);
      stream.next(m.y);
      stream.next(m.facing);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct bot_pose_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::bot_simulator::bot_pose_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::bot_simulator::bot_pose_<ContainerAllocator>& v)
  {
    s << indent << "x: ";
    Printer<float>::stream(s, indent + "  ", v.x);
    s << indent << "y: ";
    Printer<float>::stream(s, indent + "  ", v.y);
    s << indent << "facing: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.facing);
  }
};

} // namespace message_operations
} // namespace ros

#endif // BOT_SIMULATOR_MESSAGE_BOT_POSE_H
